/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/_planner'
import { Route as PlannerIndexRouteImport } from './routes/_planner.index'
import { Route as PlannerSetupRouteImport } from './routes/_planner.setup'
import { Route as PlannerReviewRouteImport } from './routes/_planner.review'

const PlannerRoute = PlannerRouteImport.update({
  id: '/_planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlannerRoute,
} as any)
const PlannerSetupRoute = PlannerSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PlannerRoute,
} as any)
const PlannerReviewRoute = PlannerReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PlannerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PlannerIndexRoute
  '/review': typeof PlannerReviewRoute
  '/setup': typeof PlannerSetupRoute
}
export interface FileRoutesByTo {
  '/review': typeof PlannerReviewRoute
  '/setup': typeof PlannerSetupRoute
  '/': typeof PlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_planner': typeof PlannerRouteWithChildren
  '/_planner/review': typeof PlannerReviewRoute
  '/_planner/setup': typeof PlannerSetupRoute
  '/_planner/': typeof PlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/review' | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/review' | '/setup' | '/'
  id:
    | '__root__'
    | '/_planner'
    | '/_planner/review'
    | '/_planner/setup'
    | '/_planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlannerRoute: typeof PlannerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_planner': {
      id: '/_planner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_planner/': {
      id: '/_planner/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/_planner/setup': {
      id: '/_planner/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof PlannerSetupRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/_planner/review': {
      id: '/_planner/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof PlannerReviewRouteImport
      parentRoute: typeof PlannerRoute
    }
  }
}

interface PlannerRouteChildren {
  PlannerReviewRoute: typeof PlannerReviewRoute
  PlannerSetupRoute: typeof PlannerSetupRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
}

const PlannerRouteChildren: PlannerRouteChildren = {
  PlannerReviewRoute: PlannerReviewRoute,
  PlannerSetupRoute: PlannerSetupRoute,
  PlannerIndexRoute: PlannerIndexRoute,
}

const PlannerRouteWithChildren =
  PlannerRoute._addFileChildren(PlannerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PlannerRoute: PlannerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
